Add key pair module
alibabacloud-automation/terraform-alicloud-key-pair pull request #1
Opened 2020-03-08 08:20 UTC by Rich-yi

2020-03-09 02:01 UTC, zql-tqy commented on README-CN.md
> +  profile                     = "Your-Profile-Name"
这个格式调一下吧

2020-03-09 02:01 UTC, zql-tqy commented on outputs.tf
> +  value = alicloud_key_pair_attachment.key_pair.*.instance_ids
缺少描述

2020-03-09 02:01 UTC, zql-tqy commented on main.tf
> +  count             = var.create_key_pair == true ? 1 : 0
bool 类型的不用判断 ==true 吧

2020-03-09 12:46 UTC, xiaozhu36 requested changes

2020-03-09 12:46 UTC, xiaozhu36 commented on main.tf
> +  count        = alicloud_key_pair.key_pair.*.key_name != null || var.create_key_pair_attachment == true ? 1 : 0
这个是干啥，就用var.create_key_pair_attachment 这一个开关就行

2020-03-10 12:33 UTC, xiaozhu36 requested changes

2020-03-10 12:33 UTC, xiaozhu36 commented on varibales.tf
> +variable "create_key_pair_attachment" {
attach

2020-03-10 12:33 UTC, xiaozhu36 commented on varibales.tf
> +variable "create_key_pair" {
create

2020-03-14 02:50 UTC, xiaozhu36 approved these changes

2020-03-14 02:50 UTC, merged